# Generated by Django 2.2.1 on 2020-07-01 06:50

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('purchases', '0002_auto_20200406_0520'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='purchase',
            table='purchases',
        ),
    ]
