# Generated by Django 2.2.1 on 2020-07-01 06:49

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('sprint_subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sprintsubscription',
            table='subscriptions_sprint',
        ),
    ]
