# Generated by Django 2.2.1 on 2020-07-01 06:50

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='plan',
            table='plans',
        ),
    ]
