# Generated by Django 2.2.1 on 2020-06-25 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AggregatedDataUsageRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('usage_date', models.DateField()),
                ('sum_kilobytes_used', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'agg_data_usage',
            },
        ),
        migrations.CreateModel(
            name='AggregatedVoiceUsageRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('usage_date', models.DateField()),
                ('sum_seconds_used', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'agg_voice_usage',
            },
        ),
    ]
