# Generated by Django 2.2.1 on 2020-07-01 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usage', '0003_auto_20200630_0547'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='aggregateddatausagerecord',
            table='usages_agg_data',
        ),
        migrations.AlterModelTable(
            name='aggregatedvoiceusagerecord',
            table='usages_agg_voice',
        ),
        migrations.AlterModelTable(
            name='datausagerecord',
            table='usages_data',
        ),
        migrations.AlterModelTable(
            name='voiceusagerecord',
            table='usages_voice',
        ),
    ]
